### ISSUE TITLE
Whacky path near stairs/elevator in basement level

### ISSUE THREAD

**Issue by markediez** [dssit/dss-wayfinding#158]
https://wayfinding.dss.ucdavis.edu/start/0242/end/0111

**Comment by jlperona** [comment]
@markediez @cmthielen I actually added a path to fix this one, the SVGs are in doc/.

I'm also curious - which set of SVGs are being used in production, one of the sets in public/maps, or the ones in doc/? I saw from #162 changes were being made to the data set in public/maps/. The ones our team linted are in doc/.
