### ISSUE TITLE
Add validations to directory objects

### ISSUE THREAD

**Issue by okadri** [dssit/dss-wayfinding#84]
Can save phone # as text currently

**Comment by retypepassword** [comment]
Fixed validations for names, e-mails, and phone numbers with 297556d2e3ad4aa26ef0d5e2dc58c35a05648466. Still missing validations for room numbers (can enter anything as a room number in the room number box, which may or may not be desirable) in department locations.

**Comment by retypepassword** [comment]
Fixed in ba6ae7d41976acf5b7b64f86912fffae1b02addd.
